wip: TargetPool failing test for HTTPS HC
Test that we can reference our new `google_compute_https_health_check`
resource. This currently fails for two reasons.

1. It seems that we're not able to provide more than one health check in the
   same request:

    --- FAIL: TestAccComputeTargetPool_health_checks (4.37s)
            testing.go:135: Step 0 error: Error applying: 1 error(s) occurred:

                    * 1 error(s) occurred:

                    * 1 error(s) occurred:

                    * Error creating TargetPool: googleapi: Error 413: Value for field 'resource.healthChecks' is too large, fieldSizeTooLarge

2. If we comment out the HTTP health check then it produces an error because
   the HTTPS health check comes from a different API version.

    --- FAIL: TestAccComputeTargetPool_health_checks (4.63s)
            testing.go:135: Step 0 error: Error applying: 1 error(s) occurred:

                    * 1 error(s) occurred:

                    * 1 error(s) occurred:

                    * Error creating TargetPool: googleapi: Error 400: Invalid value for field 'healthChecks': 'https://www.googleapis.com/compute/beta/projects/skilful-card-92510/global/healthChecks/foobar'.  URL version does not match the API version., invalid

I wonder whether it would be easier on both accounts to add each health
check individually.